platform :ios, '6.0'

target 'RSKImageCropperExampleTests', :exclusive => true do
  pod 'FBSnapshotTestCase', '1.5'
  pod 'Expecta+Snapshots', '~> 1.3'
  pod 'Specta', '0.4.0'
  pod 'Expecta', '0.3.2'
  pod 'OCMock', '2.2.4'
end
