platform :ios, '9.0'

inhibit_all_warnings!

target 'RSKImageCropperExampleTests' do
  pod 'Expecta+Snapshots', '3.1.1'
  pod 'Specta', '1.0.7'
  pod 'Expecta', '1.0.6'
  pod 'OCMock', '3.4.2'
  
  post_install do |installer|
      
      installer.pods_project.targets.each do |target|
          if target.name == 'Expecta' || target.name == 'Specta' || target.name == 'FBSnapshotTestCase'
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
              end
          end
      end
  end
end
