name: CI
on:
  pull_request:
    branches: [master]
  workflow_dispatch:
jobs:
  iOS:
    runs-on: macos-26
    env:
      DEVELOPER_DIR: '/Applications/Xcode_26.2.app/Contents/Developer'
    steps:
      - uses: actions/checkout@v6
      - name: Test
        run: make test
